require('dotenv').config();
const request = require('supertest');
const app = require('../lib/app');
const connect = require('../lib/utils/connect');
const mongoose = require('mongoose');
const SpeedDate = require('../lib/models/SpeedDate');

describe('SpeedDate routes', () => {
  
  beforeAll(() => connect());

  beforeEach(() => mongoose.connection.dropDatabase());

  let speedDate;

  beforeEach(async() => {
    speedDate = await SpeedDate.create({
      'iid': 11,
      'gender': 1,
      'idg': 2,
      'condtn': 1,
      'wave': 1,
      'round': 10,
      'position': 6,
      'positin1': 0,
      'order': 3,
      'partner': 4,
      'pid': 4,
      'match': 0,
      'int_corr': -0.18,
      'samerace': 1,
      'age_o': 23,
      'race_o': 2,
      'pf_o_att': 20,
      'pf_o_sin': 20,
      'pf_o_int': 20,
      'pf_o_fun': 20,
      'pf_o_amb': 10,
      'pf_o_sha': 10,
      'dec_o': 0,
      'attr_o': 4,
      'sinc_o': 10,
      'intel_o': 8,
      'fun_o': 5,
      'amb_o': 8,
      'shar_o': 7,
      'like_o': 6,
      'prob_o': 7,
      'met_o': 2,
      'age': 27,
      'field': 'Finance',
      'field_cd': 8,
      'undergra': 0,
      'mn_sat': 0,
      'tuition': 0,
      'race': 2,
      'imprace': 7,
      'imprelig': 3,
      'from': 'Argentina',
      'zipcode': 0,
      'income': 0,
      'goal': 1,
      'date': 5,
      'go_out': 4,
      'career': 'Academia, Research, Banking, Life',
      'career_c': 2,
      'sports': 8,
      'tvsports': 7,
      'exercise': 2,
      'dining': 6,
      'museums': 7,
      'art': 5,
      'hiking': 5,
      'gaming': 5,
      'clubbing': 4,
      'reading': 9,
      'tv': 2,
      'theater': 4,
      'movies': 8,
      'concerts': 7,
      'music': 8,
      'shopping': 5,
      'yoga': 1,
      'exphappy': 7,
      'expnum': 3,
      'attr1_1': 35,
      'sinc1_1': 20,
      'intel1_1': 20,
      'fun1_1': 20,
      'amb1_1': 0,
      'shar1_1': 5,
      'attr4_1': 0,
      'sinc4_1': 0,
      'intel4_1': 0,
      'fun4_1': 0,
      'amb4_1': 0,
      'shar4_1': 0,
      'attr2_1': 25,
      'sinc2_1': 5,
      'intel2_1': 20,
      'fun2_1': 20,
      'amb2_1': 25,
      'shar2_1': 5,
      'attr3_1': 8,
      'sinc3_1': 9,
      'fun3_1': 7,
      'intel3_1': 8,
      'amb3_1': 5,
      'attr5_1': 0,
      'sinc5_1': 0,
      'intel5_1': 0,
      'fun5_1': 0,
      'amb5_1': 0,
      'dec': 0,
      'attr': 6,
      'sinc': 7,
      'intel': 8,
      'fun': 7,
      'amb': 7,
      'shar': 5,
      'like': 6,
      'prob': 3,
      'met': 2,
      'match_es': 0,
      'attr1_s': 0,
      'sinc1_s': 0,
      'intel1_s': 0,
      'fun1_s': 0,
      'amb1_s': 0,
      'shar1_s': 0,
      'attr3_s': 0,
      'sinc3_s': 0,
      'intel3_s': 0,
      'fun3_s': 0,
      'amb3_s': 0,
      'satis_2': 7,
      'length': 2,
      'numdat_2': 0,
      'attr7_2': 0,
      'sinc7_2': 0,
      'intel7_2': 0,
      'fun7_2': 0,
      'amb7_2': 0,
      'shar7_2': 0,
      'attr1_2': 19.51,
      'sinc1_2': 17.07,
      'intel1_2': 17.07,
      'fun1_2': 17.07,
      'amb1_2': 12.2,
      'shar1_2': 17.07,
      'attr4_2': 0,
      'sinc4_2': 0,
      'intel4_2': 0,
      'fun4_2': 0,
      'amb4_2': 0,
      'shar4_2': 0,
      'attr2_2': 0,
      'sinc2_2': 0,
      'intel2_2': 0,
      'fun2_2': 0,
      'amb2_2': 0,
      'shar2_2': 0,
      'attr3_2': 8,
      'sinc3_2': 8,
      'intel3_2': 8,
      'fun3_2': 6,
      'amb3_2': 5,
      'attr5_2': 0,
      'sinc5_2': 0,
      'intel5_2': 0,
      'fun5_2': 0,
      'amb5_2': 0,
      'you_call': 0,
      'them_cal': 0,
      'date_3': 0,
      'numdat_3': 0,
      'num_in_3': 0,
      'attr1_3': 35,
      'sinc1_3': 25,
      'intel1_3': 15,
      'fun1_3': 15,
      'amb1_3': 0,
      'shar1_3': 10,
      'attr7_3': 0,
      'sinc7_3': 0,
      'intel7_3': 0,
      'fun7_3': 0,
      'amb7_3': 0,
      'shar7_3': 0,
      'attr4_3': 0,
      'sinc4_3': 0,
      'intel4_3': 0,
      'fun4_3': 0,
      'amb4_3': 0,
      'shar4_3': 0,
      'attr2_3': 0,
      'sinc2_3': 0,
      'intel2_3': 0,
      'fun2_3': 0,
      'amb2_3': 0,
      'shar2_3': 0,
      'attr3_3': 7,
      'sinc3_3': 8,
      'intel3_3': 7,
      'fun3_3': 7,
      'amb3_3': 5,
      'attr5_3': 0,
      'sinc5_3': 0,
      'intel5_3': 0,
      'fun5_3': 0,
      'amb5_3': 0,
      '__v': 0
    });
  });

  it('can create a new speedDate', () => {
    return request(app)
      .post('/api/v1/speed-dates')
      .send({
        'iid': 11,
        'gender': 1,
        'idg': 2,
        'condtn': 1,
        'wave': 1,
        'round': 10,
        'position': 6,
        'positin1': 0,
        'order': 3,
        'partner': 4,
        'pid': 4,
        'match': 0,
        'int_corr': -0.18,
        'samerace': 1,
        'age_o': 23,
        'race_o': 2,
        'pf_o_att': 20,
        'pf_o_sin': 20,
        'pf_o_int': 20,
        'pf_o_fun': 20,
        'pf_o_amb': 10,
        'pf_o_sha': 10,
        'dec_o': 0,
        'attr_o': 4,
        'sinc_o': 10,
        'intel_o': 8,
        'fun_o': 5,
        'amb_o': 8,
        'shar_o': 7,
        'like_o': 6,
        'prob_o': 7,
        'met_o': 2,
        'age': 27,
        'field': 'Finance',
        'field_cd': 8,
        'undergra': 0,
        'mn_sat': 0,
        'tuition': 0,
        'race': 2,
        'imprace': 7,
        'imprelig': 3,
        'from': 'Argentina',
        'zipcode': 0,
        'income': 0,
        'goal': 1,
        'date': 5,
        'go_out': 4,
        'career': 'Academia, Research, Banking, Life',
        'career_c': 2,
        'sports': 8,
        'tvsports': 7,
        'exercise': 2,
        'dining': 6,
        'museums': 7,
        'art': 5,
        'hiking': 5,
        'gaming': 5,
        'clubbing': 4,
        'reading': 9,
        'tv': 2,
        'theater': 4,
        'movies': 8,
        'concerts': 7,
        'music': 8,
        'shopping': 5,
        'yoga': 1,
        'exphappy': 7,
        'expnum': 3,
        'attr1_1': 35,
        'sinc1_1': 20,
        'intel1_1': 20,
        'fun1_1': 20,
        'amb1_1': 0,
        'shar1_1': 5,
        'attr4_1': 0,
        'sinc4_1': 0,
        'intel4_1': 0,
        'fun4_1': 0,
        'amb4_1': 0,
        'shar4_1': 0,
        'attr2_1': 25,
        'sinc2_1': 5,
        'intel2_1': 20,
        'fun2_1': 20,
        'amb2_1': 25,
        'shar2_1': 5,
        'attr3_1': 8,
        'sinc3_1': 9,
        'fun3_1': 7,
        'intel3_1': 8,
        'amb3_1': 5,
        'attr5_1': 0,
        'sinc5_1': 0,
        'intel5_1': 0,
        'fun5_1': 0,
        'amb5_1': 0,
        'dec': 0,
        'attr': 6,
        'sinc': 7,
        'intel': 8,
        'fun': 7,
        'amb': 7,
        'shar': 5,
        'like': 6,
        'prob': 3,
        'met': 2,
        'match_es': 0,
        'attr1_s': 0,
        'sinc1_s': 0,
        'intel1_s': 0,
        'fun1_s': 0,
        'amb1_s': 0,
        'shar1_s': 0,
        'attr3_s': 0,
        'sinc3_s': 0,
        'intel3_s': 0,
        'fun3_s': 0,
        'amb3_s': 0,
        'satis_2': 7,
        'length': 2,
        'numdat_2': 0,
        'attr7_2': 0,
        'sinc7_2': 0,
        'intel7_2': 0,
        'fun7_2': 0,
        'amb7_2': 0,
        'shar7_2': 0,
        'attr1_2': 19.51,
        'sinc1_2': 17.07,
        'intel1_2': 17.07,
        'fun1_2': 17.07,
        'amb1_2': 12.2,
        'shar1_2': 17.07,
        'attr4_2': 0,
        'sinc4_2': 0,
        'intel4_2': 0,
        'fun4_2': 0,
        'amb4_2': 0,
        'shar4_2': 0,
        'attr2_2': 0,
        'sinc2_2': 0,
        'intel2_2': 0,
        'fun2_2': 0,
        'amb2_2': 0,
        'shar2_2': 0,
        'attr3_2': 8,
        'sinc3_2': 8,
        'intel3_2': 8,
        'fun3_2': 6,
        'amb3_2': 5,
        'attr5_2': 0,
        'sinc5_2': 0,
        'intel5_2': 0,
        'fun5_2': 0,
        'amb5_2': 0,
        'you_call': 0,
        'them_cal': 0,
        'date_3': 0,
        'numdat_3': 0,
        'num_in_3': 0,
        'attr1_3': 35,
        'sinc1_3': 25,
        'intel1_3': 15,
        'fun1_3': 15,
        'amb1_3': 0,
        'shar1_3': 10,
        'attr7_3': 0,
        'sinc7_3': 0,
        'intel7_3': 0,
        'fun7_3': 0,
        'amb7_3': 0,
        'shar7_3': 0,
        'attr4_3': 0,
        'sinc4_3': 0,
        'intel4_3': 0,
        'fun4_3': 0,
        'amb4_3': 0,
        'shar4_3': 0,
        'attr2_3': 0,
        'sinc2_3': 0,
        'intel2_3': 0,
        'fun2_3': 0,
        'amb2_3': 0,
        'shar2_3': 0,
        'attr3_3': 7,
        'sinc3_3': 8,
        'intel3_3': 7,
        'fun3_3': 7,
        'amb3_3': 5,
        'attr5_3': 0,
        'sinc5_3': 0,
        'intel5_3': 0,
        'fun5_3': 0,
        'amb5_3': 0,
        '__v': 0
      })
      .then(res => {
        expect(res.body).toEqual({
          _id: expect.any(String),
          iid: 11,
          gender: 1,
          idg: 2,
          condtn: 1,
          wave: 1,
          round: 10,
          position: 6,
          positin1: 0,
          order: 3,
          partner: 4,
          pid: 4,
          match: 0,
          int_corr: -0.18,
          samerace: 1,
          age_o: 23,
          race_o: 2,
          pf_o_att: 20,
          pf_o_sin: 20,
          pf_o_int: 20,
          pf_o_fun: 20,
          pf_o_amb: 10,
          pf_o_sha: 10,
          dec_o: 0,
          attr_o: 4,
          sinc_o: 10,
          intel_o: 8,
          fun_o: 5,
          amb_o: 8,
          shar_o: 7,
          like_o: 6,
          prob_o: 7,
          met_o: 2,
          age: 27,
          field: 'Finance',
          field_cd: 8,
          undergra: 0,
          mn_sat: 0,
          tuition: 0,
          race: 2,
          imprace: 7,
          imprelig: 3,
          from: 'Argentina',
          zipcode: 0,
          income: 0,
          goal: 1,
          date: 5,
          go_out: 4,
          career: 'Academia, Research, Banking, Life',
          career_c: 2,
          sports: 8,
          tvsports: 7,
          exercise: 2,
          dining: 6,
          museums: 7,
          art: 5,
          hiking: 5,
          gaming: 5,
          clubbing: 4,
          reading: 9,
          tv: 2,
          theater: 4,
          movies: 8,
          concerts: 7,
          music: 8,
          shopping: 5,
          yoga: 1,
          exphappy: 7,
          expnum: 3,
          attr1_1: 35,
          sinc1_1: 20,
          intel1_1: 20,
          fun1_1: 20,
          amb1_1: 0,
          shar1_1: 5,
          attr4_1: 0,
          sinc4_1: 0,
          intel4_1: 0,
          fun4_1: 0,
          amb4_1: 0,
          shar4_1: 0,
          attr2_1: 25,
          sinc2_1: 5,
          intel2_1: 20,
          fun2_1: 20,
          amb2_1: 25,
          shar2_1: 5,
          attr3_1: 8,
          sinc3_1: 9,
          fun3_1: 7,
          intel3_1: 8,
          amb3_1: 5,
          attr5_1: 0,
          sinc5_1: 0,
          intel5_1: 0,
          fun5_1: 0,
          amb5_1: 0,
          dec: 0,
          attr: 6,
          sinc: 7,
          intel: 8,
          fun: 7,
          amb: 7,
          shar: 5,
          like: 6,
          prob: 3,
          met: 2,
          match_es: 0,
          attr1_s: 0,
          sinc1_s: 0,
          intel1_s: 0,
          fun1_s: 0,
          amb1_s: 0,
          shar1_s: 0,
          attr3_s: 0,
          sinc3_s: 0,
          intel3_s: 0,
          fun3_s: 0,
          amb3_s: 0,
          satis_2: 7,
          length: 2,
          numdat_2: 0,
          attr7_2: 0,
          sinc7_2: 0,
          intel7_2: 0,
          fun7_2: 0,
          amb7_2: 0,
          shar7_2: 0,
          attr1_2: 19.51,
          sinc1_2: 17.07,
          intel1_2: 17.07,
          fun1_2: 17.07,
          amb1_2: 12.2,
          shar1_2: 17.07,
          attr4_2: 0,
          sinc4_2: 0,
          intel4_2: 0,
          fun4_2: 0,
          amb4_2: 0,
          shar4_2: 0,
          attr2_2: 0,
          sinc2_2: 0,
          intel2_2: 0,
          fun2_2: 0,
          amb2_2: 0,
          shar2_2: 0,
          attr3_2: 8,
          sinc3_2: 8,
          intel3_2: 8,
          fun3_2: 6,
          amb3_2: 5,
          attr5_2: 0,
          sinc5_2: 0,
          intel5_2: 0,
          fun5_2: 0,
          amb5_2: 0,
          you_call: 0,
          them_cal: 0,
          date_3: 0,
          numdat_3: 0,
          num_in_3: 0,
          attr1_3: 35,
          sinc1_3: 25,
          intel1_3: 15,
          fun1_3: 15,
          amb1_3: 0,
          shar1_3: 10,
          attr7_3: 0,
          sinc7_3: 0,
          intel7_3: 0,
          fun7_3: 0,
          amb7_3: 0,
          shar7_3: 0,
          attr4_3: 0,
          sinc4_3: 0,
          intel4_3: 0,
          fun4_3: 0,
          amb4_3: 0,
          shar4_3: 0,
          attr2_3: 0,
          sinc2_3: 0,
          intel2_3: 0,
          fun2_3: 0,
          amb2_3: 0,
          shar2_3: 0,
          attr3_3: 7,
          sinc3_3: 8,
          intel3_3: 7,
          fun3_3: 7,
          amb3_3: 5,
          attr5_3: 0,
          sinc5_3: 0,
          intel5_3: 0,
          fun5_3: 0,
          amb5_3: 0,
          __v: 0
        });
      });
  });

  it('gets a speed date by id', () => {
    return request(app)
      .get(`/api/v1/speed-dates/${speedDate.id}`)
      .then(res => {
        expect(res.body).toEqual({
          ...speedDate.toJSON(),
          _id: speedDate.id,
        });
      });
  });

  it('gets all speed dates', () => {
    return request(app)
      .get('/api/v1/speed-dates')
      .then(res => {
        expect(res.body).toEqual([
          {
            ...speedDate.toJSON(),
            _id: speedDate.id,
          }
        ]);
      });
  });

  it('updates a speedDate', () => {
    return request(app)
      .patch(`/api/v1/speed-dates/${speedDate.id}`)
      .send({ zipcode: 97201 })
      .then(res => {
        expect(res.body).toEqual({
          ...speedDate.toJSON(),
          _id: speedDate.id,
          zipcode: 97201
        });
      });
  });

  it('deletes a speed date', () => {
    return request(app)
      .delete(`/api/v1/speed-dates/${speedDate.id}`)
      .then(res => {
        expect(res.body).toEqual({
          ...speedDate.toJSON(),
          _id: speedDate.id,
        });
      });
  });
});

afterAll(() => mongoose.connection.close());
